version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile.cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]